config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  root to: 'v4/pages#home_v4'

  mount ActionCable.server => '/cable'
  # handle websocket for messagerie
  resources :chatrooms
  resources :chat_messages
  resources :customer_requests, only: [:create]

  # Api version of bcs
  namespace :api do
    namespace :agency do
      resources :agencies, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "agencies#status"
    end
    namespace :customer do
      resources :customers, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "customers#status"
    end
  end

  namespace :rent do
    resources :agencies
  end

  namespace :apifluxes do
    resources :properties
    resources :agencies
    post "activate_agency_flux_recovery/:id", to: "agencies#activate_agency_flux_recovery", as: "activate_flux"
  end

  post 'activate_rent_agency', to: "rent/agencies#activate"
  post 'deactivate_rent_agency', to: "rent/agencies#deactivate"

  get 'widgets/:id/:template/', to: 'widgets#show'
  get 'widgets/iframe_version', to: 'widgets#iframe_version'

  get "estimations/new_estimation", to: "estimations#new_estimation", as: "new_estimation"

  get "sending_sms", to: "phone_messages#sending_sms", as: "sending_sms"
  get "change_property_status/:id", to: "properties#change_status", as: "change_status"


  namespace :webhooks do
    post "releases", to: "heroku#releases", as: "releases"
    post "builds", to: "heroku#builds", as: "builds"
    post "app", to: "heroku#app", as: "app"
    post "submit", to: "typeform#submit", as: "submit"
    post "sent", to: "mandrill#sent", as: "sent"
    post "open", to: "mandrill#open", as: "open"
    post "click", to: "mandrill#click", as: "click"
    post "build", to: "codeship#build", as: "build"
    post "delivery", to: "nexmo#delivery", as: "delivery"
    post "malab/submit", to: "malab#submit", as: "malab_submit"
    get "malab_view", to: "pages#malab_view", as: "malab_view"
    get "sent", to: "mandrill#sent"
    get "open", to: "mandrill#open"
    get "click", to: "mandrill#click"
    get "list", to: "pages#list", as: "list"
    get "typeform_list", to: "pages#typeform_list", as: "typeform_list"
    get "visits", to: "pages#visits", as: "visits"
    post "survey", to: "aristid#survey", as: "survey"
    get "aristid/test", to: "aristid#test", as: "aristid_test"
    get "aristid/initial_request", to: "aristid#initial_request"
    post "aristid/initial_request", to: "aristid#initial_request", as: "initial_request"
  end


  namespace :analytics do
    get "demands", to: "demands#index", as: "demands"
    get "demands/:id", to: "demands#show", as: "demand"
  end

  namespace :v4 do
    get "new-home", to: "pages#home_v4", as: "home_v4"
    get "matching_algo_test", to: "pages#matching_algo_test", as: "matching_algo_test"
  end

  namespace :typeform do
    get "advanced_input_return", to: "rents#advanced_input_return", as: "advanced_input_return"
    get "advanced_input", to: "rents#advanced_input", as: "advanced_input"
    get "responses", to: "rents#responses", as: "responses"
    get "mail_response", to: "rents#mail_response", as: "mail_response"
    get "persisted_typeforms", to: "rents#persisted_typeforms", as: "persisted_typeforms"
    get "mailer_test", to: "rents#mailer_test", as: "mailer_test"
  end

  namespace :access do
    resources :properties
    get "success", to: "properties#success", as: "success"
    get "service_test", to: "properties#service_test", as: "service_test"
    get "budget_script", to: "properties#handle_demands_budget_to_integer", as: "budget_script"
    get "new_mailer", to: "properties#all_offers_without_choice", as: "new_mailer"
  end

  namespace :v2 do
    get "test_api_connect", to: "pages#test_api_connect", as: 'test_api_connect'
    resources :v2_demands
    get "results", to: "v2_demands#results", as: "results"
    get "ajax_query", to: "v2_demands#influence_ajax_query", as: "influence_ajax_query"

    get "pdf", to: "pdfs#show", as: "pdf"
    get "demand-stats", to: "pages#demand_stats", as: "demand_stats"
    get "migrations", to: "pages#migrations", as: "migrations"
    get "new-survey", to: "pages#new_survey", as: "new_survey"
    post "next-question", to: "pages#next_question", as: "next_survey_v2"
    post "last-question", to: "pages#last_question", as: "last_survey_v2"
    post "next-question-on-skip", to: "pages#next_question_on_skip", as: "next_survey_on_skip"
    get "demand-view", to: "pages#demand_view", as: "demand_view"
    post "orderable", to: "pages#orderable", as: "survey_orderable"
    post "new-question", to: "pages#new_question", as: "new_question"
    get "test-new-survey", to: "pages#test_new_survey", as: "test_new_survey"
    post "test-next-question", to: "pages#test_next_question", as: "test_next_question"
    post "criterias-v2", to: "pages#criterias", as: "criterias_v2"
    get "summary", to: "pages#summary", as: "summary"
    get "map", to: "pages#map", as: "map"
    get "start", to: "pages#start", as: "start"
    post "multi_circle_batch_constructor", to: "pages#multi_circle_batch_constructor", as: "mcbc"
    get "dashboard", to: "customers#home", as: "old_customer_dashboard"
    resources :questions, only: [:edit, :update]
    resources :sentences, only: [:edit, :update]
    resources :v2_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :v2_answers, only: [:new, :create, :edit, :update]
    get "week_stats", to: "statistics#week_stats", as: "week_stats"

    # Arthur routing
    get "dashboard/agency/home", to: "agencies#home", as: "agency_dashboard"
    get "dashboard/agency/props_waiting_for_choice", to: "agencies#props_waiting_for_choice", as: "props_waiting_for_choice"
    get "dashboard/agency/demands", to: "agencies#demands", as: "dashboard_agency_demands"
    get "dashboard/agency/properties", to: "agencies#properties", as: "dashboard_agency_properties"
    get "bcs-property-show", to: "agencies#property_show", as: "bcs_property_show"
    get "dashboard/agency/pending_offers", to: "agencies#pending_offers", as: "dashboard_agency_pending_offers"
    get 'dashboard/agency/demand/:demand_id', to: "agencies#demand", as: "dashboard_agency_demand"
    post "dashboard/agency/demands/search_with_ajax", to: "agencies#search_with_ajax", as: "dashboard_agency_demands_search_with_ajax"

    get "ajaxified_customer_choice", to: "customer_choices#customer_choice_ajax", as: "ajaxified_choices"

    # New customer dashboard routing
    get "dashboard/customer/home", to: "customers#home", as: "customer_dashboard"
    get "dashboard/customer/mes_petits_plus", to: "customers#my_little_mores", as: "mores"
    get "dashboard/customer/advices", to: "customers#advices", as: "advices"
    get "dashboard/customer/journey", to: "customers#journey", as: "journey"
    get "dashboard/customer/selection", to: "customers#selection", as: "selection"
    get "dashboard/customer/properties", to: "customers#properties", as: "customer_dashboard_properties"
    get "dashboard/customer/properties/:property_id", to: "customers#property", as: "customer_dashboard_property"
    get "dashboard/customer/messages", to: "customers#messages", as: "customer_dashboard_messages"
    post "dashboard/customer/properties/:property_id/hate", to: "customer_choices#hate", as: "customer_choice_hate"
    post "dashboard/customer/properties/:property_id/like", to: "customer_choices#like", as: "customer_choice_like"
    post "dashboard/customer/properties/customer_unlike_choice_ajax", to: "customers#customer_unlike_choice_ajax", as: "customer_dashboard_properties_customer_unlike_choice_ajax"
    post "dashboard/customer/properties/customer_like_choice_ajax", to: "customers#customer_like_choice_ajax", as: "customer_dashboard_properties_customer_like_choice_ajax"

  end

  get "s3_migration", to: "pages#s3_to_cloudinary_migration", as: "s3_migration"
  get "s3_migration_for_hektor", to: "pages#s3_migration_for_hektor_flux", as: "s3_hektor_migration"

  get "test_unviewed_demands_mailing", to: "pages#test_unviewed_demands_mailing", as: "mailing_test"
  get "dico-de-kenotte", to: "pages#glossary", as: "glossary"
  get "bcs-properties", to: "pages#bcs_properties", as: "exclu_bcs_properties"
  get "bcs-property-show", to: "pages#bcs_property_show", as: "home_bcs_property_show"
  get "estimation", to: "pages#estimation_v3", as: "estimation_v3"
  get "devenir-partenaire", to: "pages#partner_landing", as: "partner_landing"
  get "estimation-v2", to: "pages#estimation_v2", as: "estimation_v2"
  get "employee-model-test", to: 'pages#employee_test', as: "employee"
  get "email-job-testing", to: 'pages#email_job_testing', as: "email_job_testing"
  get "partenaires", to: "pages#partners", as: "static_partners"
  get "ajax-upload", to: "properties#ajax_photo_upload", as: "ajax_upload"
  get "conversation", to: "conversations#conversation", as: "conversation"
  post "conversation", to: "conversations#new_message", as: "conversation_message"
  get "faq", to: "pages#faq", as: "faq"

  resources :demands, only: [:create, :destroy]
  resources :sponsorships, only: [:create]
  resources :customer_advices, only: [:create]
  resources :contacts, only: [:create]
  resources :customer_questions, only: [:create]
  resources :newsletters, only: [:create]
  resources :key_facts, only: [:create]
  resources :candidacies, only: [:create]
  resources :estimations, only: [:create]
  resources :presskit_requests, only: [:create]

  resources :partners

  get "keyfact-creation", to: "key_facts#new"
  get "espace-presse", to: "pages#presse", as: "presse"
  get "chasse-immobiliere", to: "pages#hunt", as: "hunt"


  namespace :admin do
    resources :estimations, only: [:show, :index, :destroy]
    resources :press_releases, only: [:new, :show, :index, :create, :destroy, :edit, :update]

app/views/home/_home_properties_slider.html.haml
.home-properties-slider-wrapper

app/views/home/_home_props_slider.html.haml
.menu-wrapper#props-wrapper
  .header-title
    .inline-svg.mr-10.black
      = svg("panneau")
    - if estimation_title
      = estimation_title
    - else
      en agence actuellement
  %ul.menu#slider-menu
    %button.left-paddle.paddle
      %i.fa.fa-arrow-left{"aria-hidden" => "true"}
    .faded-block.left
    - @bcs_properties.sort_by{|prop| prop.created_at}.reverse.each_with_index do |prop,index|
      %li.item{class: "#{'last-item' if ((index + 1) == (@bcs_properties.size))}"}
        = link_to home_bcs_property_show_path(property_id: prop.id.to_s), target: "_blank" do
          .home-slider-prop-card
            - if prop.img_1_url
              .slider-home-card-top{style: "background-image: url(#{prop.img_1_url});"}
                - if prop.status
                  .status-banner
                    = property_status_format(prop.status)
            - else
              .slider-home-card-top{style: "background-image: url(#{asset_path 'Logo-bulle-2.png'});"}
            .slider-home-card-bottom
              .slider-bottom-item
                .title
                  - if prop.title
                    = prop.title.truncate(31)
                  - elsif prop.titre
                    = prop.titre
              .slider-bottom-item.between
                .between-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-surface.svg", width: "18"
                  = "#{prop.area} m²"
                .between-item
                  - if prop.price
                    .price
                      = "#{number_with_delimiter(prop.price.gsub(/\u00a0/, '').to_i, locale: :fr)} €"

              - if prop.property_type == "Maison"
                .slider-bottom-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-house.svg", width: "20"
                  .prop-type
                    = prop.property_type
              - elsif prop.property_type == "Appartement"
                .slider-bottom-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-flat.svg", width: "18"
                  .prop-type
                    = prop.property_type

              .slider-bottom-item
                = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-marker.svg", width: "14"
                .localisation
                  - if prop.cp && prop.ville
                    = "#{prop.cp}, #{prop.ville}"
                  - if prop.zipcode && prop.localisation
                    = ("#{prop.zipcode}, #{prop.localisation}").truncate(26)


    .faded-block.right
    %button.right-paddle.paddle
      %i.fa.fa-arrow-right{"aria-hidden" => "true"}

app/views/home/_home_props_slider_last_element.html.haml
.menu-wrapper#props-wrapper{class: "zero-margins"}
  .header-title
    - if estimation_title
      = estimation_title
    - else
      en agence actuellement
  %ul.menu#slider-menu
    %button.left-paddle.paddle
      %i.fa.fa-arrow-left{"aria-hidden" => "true"}
    .faded-block.left
    - @bcs_properties.each_with_index do |prop,index|
      %li.item{class: "#{'last-item' if ((index + 1) == (@bcs_properties.size))}"}
        = link_to home_bcs_property_show_path(property_id: prop.id.to_s), target: "_blank" do
          .home-slider-prop-card
            - if prop.img_1_url
              .slider-home-card-top{style: "background-image: url(#{prop.img_1_url});"}
            - else
              .slider-home-card-top{style: "background-image: url(#{asset_path 'Logo-bulle-2.png'});"}
            .slider-home-card-bottom
              .slider-bottom-item
                .title
                  - if prop.title
                    = prop.title.truncate(31)
                  - elsif prop.titre
                    = prop.titre
              .slider-bottom-item.between
                .between-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-surface.svg", width: "18"
                  = "#{prop.area} m²"
                .between-item
                  - if prop.price
                    .price
                      = "#{number_with_delimiter(prop.price.gsub(/\u00a0/, '').to_i, locale: :fr)} €"

              - if prop.property_type == "Maison"
                .slider-bottom-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-house.svg", width: "20"
                  .prop-type
                    = prop.property_type
              - elsif prop.property_type == "Appartement"
                .slider-bottom-item
                  = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-flat.svg", width: "18"
                  .prop-type
                    = prop.property_type

              .slider-bottom-item
                = image_tag "https://cdn.bientotchezsoi-dev.com/images/picto-marker.svg", width: "14"
                .localisation
                  - if prop.cp && prop.ville
                    = "#{prop.cp}, #{prop.ville}"
                  - if prop.zipcode && prop.localisation
                    = ("#{prop.zipcode}, #{prop.localisation}").truncate(26)


    .faded-block.right
    %button.right-paddle.paddle
      %i.fa.fa-arrow-right{"aria-hidden" => "true"}

app/views/home/_home_slider.html.haml
#carousel-example-generic.carousel{'data-ride':'carousel'}
  .carousel-inner{role:"listbox"}
    .item.active
      .absolute-content.flex-column.slider-item{style:"background-image: linear-gradient(rgba(40,40,40,0.5),rgba(40,40,40,0.5)), url('https://cdn.bientotchezsoi-dev.com/images/home-banner-test.jpg');"}
        %h1
          = t('home.slider.item_1.title')
        = link_to "JE DECOUVRE", root_path, class: "bcs-button"
    .item
      .absolute-content.slider-item{style:"background-image: linear-gradient(rgba(40,40,40,0.5),rgba(40,40,40,0.5)), url('https://cdn.bientotchezsoi-dev.com/images/living-room.jpeg');"}
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/demenagement.png", class: 'logo-sm hidden-xs'
        .flex-half-dynamic
          %h1
            = t('home.slider.item_2.title')
          %p
            = t('home.slider.item_2.sub_title')
    .item
      .absolute-content.slider-item{style:"background-image: linear-gradient(rgba(40,40,40,0.5),rgba(40,40,40,0.5)),url('https://cdn.bientotchezsoi-dev.com/images/living-room.jpeg');"}
        %h1
          = t('home.slider.item_3.title')
  %a.left.carousel-control{href:"#carousel-example-generic",role:"button",'data-slide':"prev"}
    %span.glyphicon.glyphicon-chevron-left{'aria-hidden':'true'}
    %span.sr-only

  %a.right.carousel-control{href:"#carousel-example-generic", role:"button", 'data-slide':"next"}
    %span.glyphicon.glyphicon-chevron-right{'aria-hidden':'true'}
    %span.sr-only

app/views/home/_home_slider_v2.html.haml
.home-banner
  .banner-ufo-svg
    = svg("soucoupe")
  .absolute-marketplace-banner.hidden
    La 1ère place de marché de l'immobilier
  .content
    .home-banner-content-header
      %div.visible-title
        a la recherche de la perle rare à acheter ?
      %div.hidden-title
        un achat coup de ❤️ !
      %div.visible-title
        trouvons votre coup de ❤️ !
      %div.hidden-title
        par ici
    = form_tag(initial_location_path, method: :post,id: "initial_location") do
      .inline-form
        %input.user-city-choice{id:"user_input_autocomplete_address",placeholder:"Où voulez-vous vivre ?",autocomplete:"off"}
        %input{id:"lng",name:"lng",type:"hidden"}
        %input{id:"lat",name:"lat",type:"hidden"}
        %input{id:"locality",name:"locality",type:"hidden"}
        %input.user-choice-submit{type:"submit", value: "JE CHERCHE"}

app/views/home/_horizontal_slider.html.haml
.menu-wrapper
  %ul.menu
    %li.item
      = link_to "https://www.bienici.com/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/BIEN-ICI.png", width: "100"
    %li.item
      = link_to "https://www.meilleursagents.com/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/meilleurs-agent-logo.png", width: "120"
    %li.item
      = link_to "https://www.la-boite-immo.com/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/LABOITE-IMMO.png", width: "120"
    %li.item
      = link_to "https://www.hubstairs.com/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/hubstairs-logo.png", width: "120"
    %li.item
      = link_to "http://www.emprunt-cub-pret-immobilier.fr/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/pictos/emprunt-cub-logo.png", width: "120"
    %li.item
      = link_to "https://horizon1641-immo.fr/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/svgs/horizon-vices-cache.png", width: "110"
    %li.item
      = link_to "https://www.pickup.fr/accueil/bienvenue.sls", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/svgs/pickup-svg-logo.svg", width: "110"
    %li.item
      = link_to "https://www.helagis.com/", target: "_blank" do
        = image_tag "https://cdn.bientotchezsoi-dev.com/svgs/Helagis.svg", width: "110"

  .paddles
    %button.left-paddle.paddle
      %i.fa.fa-arrow-left{"aria-hidden" => "true"}
    %button.right-paddle.paddle
      %i.fa.fa-arrow-right{"aria-hidden" => "true"}

app/views/home/home.html.haml
= render 'home/home_slider'

%section.home-section
  .row
    .col-xs-12.col-md-4.col-lg-4
      .home-card
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/castor-maison.png"
        .title
          = t('home.home_actions.item_1.title')
        .title
          = t('home.home_actions.item_1.sub_title')
        .content
          = t('home.home_actions.item_1.content').html_safe
        .d-flex-center.flex-grow
          = link_to 'JE RECHERCHE', root_path, class: 'bcs-button flex-grow'

    .col-xs-12.col-md-4.col-lg-4
      .home-card
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/castor-Contrat.png"
        .title
          = t('home.home_actions.item_2.title')
        .title
          = t('home.home_actions.item_2.sub_title')
        .content
          = t('home.home_actions.item_2.content').html_safe
        .d-flex-center.flex-grow
          = link_to 'JE VENDS', root_path, class:'bcs-button flex-grow'

    .col-xs-12.col-md-4.col-lg-4
      .home-card
        = image_tag "https://cdn.bientotchezsoi-dev.com/images/question-home.png"
        .title
          = t('home.home_actions.item_3.title')
        .title
          = t('home.home_actions.item_3.sub_title')
        .content
          = t('home.home_actions.item_3.content').html_safe
        .d-flex-center.flex-grow
          = link_to "JE M'INFORME", root_path, class: 'bcs-button flex-grow'

%section.home-section.bordered.bck-dark-light
  %h1.big-title.text-center
    = t('home.video.title')
  .d-flex-center
    .video-container
      %video{controls:true}
        %source{type:"video/mp4",src:"https://cdn.bientotchezsoi-dev.com/images/presentation-bientotchezsoi_1.mp4"}

%section.home-section.bck-green
  %h1.text-center
    = t('home.news.title')
  .row
    .col-xs-12.col-md-6
      .blog-card
        .top-section{style:"background-image: url('https://via.placeholder.com/450x250');"}
          .absolute-layout
            .plus-logo
              +
        .bottom-section
          %h4
            ACHETER A DEUX ET RESTER HEUREUX !
          .d-flex-start
            %small
              31/01/2018 |
            %small.card-category
              Achat
          %p
            Un achat à deux représente une étape importante dans la vie d’un couple, le début d’une grande aventure. S’il s’agit d’un avantage indéniable pour obtenir un financement plus facilement, il est important de mesurer aussi les compromis à faire ensemble…
          = link_to "Lire la suite", root_path, class: "blog-card-link"

    .col-xs-12.col-md-6
      .blog-card
        .top-section{style:"background-image: url('https://via.placeholder.com/450x250');"}
          .absolute-layout
            .plus-logo
              +
        .bottom-section
          %h4
            REUSSIR VOTRE VENTE : LE COACHING DE KENOTTE !
          .d-flex-start
            %small
              31/01/2018 |
            %small.card-category
              Vente
          %p
            Vous avez fixé le prix de vente de votre bien de manière réaliste et objective, et l’avez mis en valeur au mieux ? C’est parti pour les visites ! Commencez par accueillir les acquéreurs potentiels avec le sourire : la première impression est primordiale...
          = link_to "Lire la suite", root_path, class: "blog-card-link"

  .d-flex-center
    = link_to 'TOUS LES ARTICLES', root_path, class: "bcs-button mt-25"

%section.home-section
  %h1.big-title.text-center
    = t('home.compliments.title')
  .row
    .col-xs-12.col-md-4
      .testimonial-card.bck-dark-light
        .logo-absolute-container
          .quote-logo
            ❞
        %p.content
          = t('home.compliments.item_1.content')
        .bottom
          %h4
            %strong
              = t('home.compliments.item_1.user')
          %h4
            = t('home.compliments.item_1.user_job')

    .col-xs-12.col-md-4
      .testimonial-card.bck-dark-light
        .logo-absolute-container
          .quote-logo
            ❞
        %p.content
          = t('home.compliments.item_2.content')
        .bottom
          %h4
            %strong
              = t('home.compliments.item_2.user')
          %h4
            = t('home.compliments.item_2.user_job')

    .col-xs-12.col-md-4
      .testimonial-card.bck-dark-light
        .logo-absolute-container
          .quote-logo
            ❞
        %p.content
          = t('home.compliments.item_3.content')
        .bottom
          %h4
            %strong
              = t('home.compliments.item_3.user')
          %h4
            = t('home.compliments.item_3.user_job')

%section.home-section.bck-dark-light
  %h1.big-title.text-center
    = t('home.engagements.title')
  %h5.text-center
    = t('home.engagements.sub_title')
  .row
    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/ampoule.png');"}
        %h4
          = t('home.engagements.item_1.title')
    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/Castor-TeteClindoeil.png');"}
        %h4
          = t('home.engagements.item_2.title')
    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/Cadenas.png');"}
        %h4
          = t('home.engagements.item_3.title')
    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/Coeur.png');"}
        %h4
          = t('home.engagements.item_4.title')

%section.home-section
  %h1.big-title.text-center
    = t('home.partners.title')
  %h5.text-center
    = t('home.partners.sub_title')
  .row
    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo-wider{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/FNAIM.png');"}

    %div.col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo-wider{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/FRENCH-TECH.png');"}

    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo-wider{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/LABOITE-IMMO.png');"}

    .col-xs-12.col-md-6.col-lg-3
      .partner-card
        .partner-card-photo-wider{style:"background-image: url('https://cdn.bientotchezsoi-dev.com/images/BIEN-ICI.png');"}

%section.home-section.bordered.bck-orange
  .row
    .col-xs-12
      .d-flex-center.flex-column
        %h1.big-title
          = t('home.form.title')
        %p
          = t('home.form.sub_title')
  .d-flex-center
    .left-content
      %form.form-home{action:""}
        %row
          .col-xs-12.col-md-6
            %input{type:"text", placeholder:"Mon nom"}
          .col-xs-12.col-md-6
            %input{type:"text", placeholder:"Mon prénom"}

          .col-xs-12.col-md-6
            %input{type:"email", placeholder:"Mon adresse e-mail"}
          .col-xs-12.col-md-6
            %input{type:"phone", placeholder:"Mon numéro de téléphone(facultatif)"}

          .col-xs-12
            %fieldset
              %legend
                La bonne case cochée permet d’avoir accès vite au bon expert à vos côtés !
              %div
                .d-flex-start.mb-10
                  %input#contactChoice1{type:"radio",name:"contact",value:"coup-de-coeur",checked:true}
                  %label{for:"contactChoice1"}
                    Je veux un coup de coeur, je cherche !
                .d-flex-start.mb-10
                  %input#contactChoice2{type:"radio", name:"contact", value:"construction"}
                  %label{for:"contactChoice2"}
                    Je prends une feuille blanche, j'aimerais construire !
                .d-flex-start.mb-10
                  %input#contactChoice3{type:"radio", name:"contact", value:"vendre"}
                  %label{for:"contactChoice3"}
                    Je tourne une page, je vends !

          .col-xs-12
            %textarea{placeholder:"Ici, j'écris ce que j'aime dans mon logement actuel... ou autre chose"}

          %input.bcs-button-alt{type:"submit"}

    .right-content.hidden-xs
      = image_tag 'https://cdn.bientotchezsoi-dev.com/images/castor-mail.png'

app/views/home/test-agency.html.haml
= @agencies.size
- @agencies.each do |new_agency|
  %h3
    = "Agence : #{new_agency.name}"
  - old_base_agency = Agency.all.where(name: new_agency.name)
  - if old_base_agency != []
    %h2
      = "Agence Vieille base => #{old_base_agency.last}"
  - new_agency.attributes.each do |attr|
    %div
      = "#{attr.first} => #{attr.last}"