config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  root to: 'v4/pages#home_v4'

  mount ActionCable.server => '/cable'
  # handle websocket for messagerie
  resources :chatrooms
  resources :chat_messages
  resources :customer_requests, only: [:create]

  # Api version of bcs
  namespace :api do
    namespace :agency do
      resources :agencies, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "agencies#status"
    end
    namespace :customer do
      resources :customers, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "customers#status"
    end
  end

  namespace :rent do
    resources :agencies
  end

  namespace :apifluxes do
    resources :properties
    resources :agencies
    post "activate_agency_flux_recovery/:id", to: "agencies#activate_agency_flux_recovery", as: "activate_flux"
  end

  post 'activate_rent_agency', to: "rent/agencies#activate"
  post 'deactivate_rent_agency', to: "rent/agencies#deactivate"

  get 'widgets/:id/:template/', to: 'widgets#show'
  get 'widgets/iframe_version', to: 'widgets#iframe_version'

  get "estimations/new_estimation", to: "estimations#new_estimation", as: "new_estimation"

  get "sending_sms", to: "phone_messages#sending_sms", as: "sending_sms"
  get "change_property_status/:id", to: "properties#change_status", as: "change_status"


  namespace :webhooks do
    post "releases", to: "heroku#releases", as: "releases"
    post "builds", to: "heroku#builds", as: "builds"
    post "app", to: "heroku#app", as: "app"
    post "submit", to: "typeform#submit", as: "submit"
    post "sent", to: "mandrill#sent", as: "sent"
    post "open", to: "mandrill#open", as: "open"
    post "click", to: "mandrill#click", as: "click"
    post "build", to: "codeship#build", as: "build"
    post "delivery", to: "nexmo#delivery", as: "delivery"
    post "malab/submit", to: "malab#submit", as: "malab_submit"
    get "malab_view", to: "pages#malab_view", as: "malab_view"
    get "sent", to: "mandrill#sent"
    get "open", to: "mandrill#open"
    get "click", to: "mandrill#click"
    get "list", to: "pages#list", as: "list"
    get "typeform_list", to: "pages#typeform_list", as: "typeform_list"
    get "visits", to: "pages#visits", as: "visits"
    post "survey", to: "aristid#survey", as: "survey"
    get "aristid/test", to: "aristid#test", as: "aristid_test"
    get "aristid/initial_request", to: "aristid#initial_request"
    post "aristid/initial_request", to: "aristid#initial_request", as: "initial_request"
  end


  namespace :analytics do
    get "demands", to: "demands#index", as: "demands"
    get "demands/:id", to: "demands#show", as: "demand"
  end

  namespace :v4 do
    get "new-home", to: "pages#home_v4", as: "home_v4"
    get "matching_algo_test", to: "pages#matching_algo_test", as: "matching_algo_test"
  end

  namespace :typeform do
    get "advanced_input_return", to: "rents#advanced_input_return", as: "advanced_input_return"
    get "advanced_input", to: "rents#advanced_input", as: "advanced_input"
    get "responses", to: "rents#responses", as: "responses"
    get "mail_response", to: "rents#mail_response", as: "mail_response"
    get "persisted_typeforms", to: "rents#persisted_typeforms", as: "persisted_typeforms"
    get "mailer_test", to: "rents#mailer_test", as: "mailer_test"
  end

  namespace :access do
    resources :properties
    get "success", to: "properties#success", as: "success"
    get "service_test", to: "properties#service_test", as: "service_test"
    get "budget_script", to: "properties#handle_demands_budget_to_integer", as: "budget_script"
    get "new_mailer", to: "properties#all_offers_without_choice", as: "new_mailer"
  end

  namespace :v2 do
    get "test_api_connect", to: "pages#test_api_connect", as: 'test_api_connect'
    resources :v2_demands
    get "results", to: "v2_demands#results", as: "results"
    get "ajax_query", to: "v2_demands#influence_ajax_query", as: "influence_ajax_query"

    get "pdf", to: "pdfs#show", as: "pdf"
    get "demand-stats", to: "pages#demand_stats", as: "demand_stats"
    get "migrations", to: "pages#migrations", as: "migrations"
    get "new-survey", to: "pages#new_survey", as: "new_survey"
    post "next-question", to: "pages#next_question", as: "next_survey_v2"
    post "last-question", to: "pages#last_question", as: "last_survey_v2"
    post "next-question-on-skip", to: "pages#next_question_on_skip", as: "next_survey_on_skip"
    get "demand-view", to: "pages#demand_view", as: "demand_view"
    post "orderable", to: "pages#orderable", as: "survey_orderable"
    post "new-question", to: "pages#new_question", as: "new_question"
    get "test-new-survey", to: "pages#test_new_survey", as: "test_new_survey"
    post "test-next-question", to: "pages#test_next_question", as: "test_next_question"
    post "criterias-v2", to: "pages#criterias", as: "criterias_v2"
    get "summary", to: "pages#summary", as: "summary"
    get "map", to: "pages#map", as: "map"
    get "start", to: "pages#start", as: "start"
    post "multi_circle_batch_constructor", to: "pages#multi_circle_batch_constructor", as: "mcbc"
    get "dashboard", to: "customers#home", as: "old_customer_dashboard"
    resources :questions, only: [:edit, :update]
    resources :sentences, only: [:edit, :update]
    resources :v2_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :v2_answers, only: [:new, :create, :edit, :update]
    get "week_stats", to: "statistics#week_stats", as: "week_stats"

    # Arthur routing
    get "dashboard/agency/home", to: "agencies#home", as: "agency_dashboard"
    get "dashboard/agency/props_waiting_for_choice", to: "agencies#props_waiting_for_choice", as: "props_waiting_for_choice"
    get "dashboard/agency/demands", to: "agencies#demands", as: "dashboard_agency_demands"
    get "dashboard/agency/properties", to: "agencies#properties", as: "dashboard_agency_properties"
    get "bcs-property-show", to: "agencies#property_show", as: "bcs_property_show"
    get "dashboard/agency/pending_offers", to: "agencies#pending_offers", as: "dashboard_agency_pending_offers"
    get 'dashboard/agency/demand/:demand_id', to: "agencies#demand", as: "dashboard_agency_demand"
    post "dashboard/agency/demands/search_with_ajax", to: "agencies#search_with_ajax", as: "dashboard_agency_demands_search_with_ajax"

    get "ajaxified_customer_choice", to: "customer_choices#customer_choice_ajax", as: "ajaxified_choices"

    # New customer dashboard routing
    get "dashboard/customer/home", to: "customers#home", as: "customer_dashboard"
    get "dashboard/customer/mes_petits_plus", to: "customers#my_little_mores", as: "mores"
    get "dashboard/customer/advices", to: "customers#advices", as: "advices"
    get "dashboard/customer/journey", to: "customers#journey", as: "journey"
    get "dashboard/customer/selection", to: "customers#selection", as: "selection"
    get "dashboard/customer/properties", to: "customers#properties", as: "customer_dashboard_properties"
    get "dashboard/customer/properties/:property_id", to: "customers#property", as: "customer_dashboard_property"
    get "dashboard/customer/messages", to: "customers#messages", as: "customer_dashboard_messages"
    post "dashboard/customer/properties/:property_id/hate", to: "customer_choices#hate", as: "customer_choice_hate"
    post "dashboard/customer/properties/:property_id/like", to: "customer_choices#like", as: "customer_choice_like"
    post "dashboard/customer/properties/customer_unlike_choice_ajax", to: "customers#customer_unlike_choice_ajax", as: "customer_dashboard_properties_customer_unlike_choice_ajax"
    post "dashboard/customer/properties/customer_like_choice_ajax", to: "customers#customer_like_choice_ajax", as: "customer_dashboard_properties_customer_like_choice_ajax"

  end

  get "s3_migration", to: "pages#s3_to_cloudinary_migration", as: "s3_migration"
  get "s3_migration_for_hektor", to: "pages#s3_migration_for_hektor_flux", as: "s3_hektor_migration"

  get "test_unviewed_demands_mailing", to: "pages#test_unviewed_demands_mailing", as: "mailing_test"
  get "dico-de-kenotte", to: "pages#glossary", as: "glossary"
  get "bcs-properties", to: "pages#bcs_properties", as: "exclu_bcs_properties"
  get "bcs-property-show", to: "pages#bcs_property_show", as: "home_bcs_property_show"
  get "estimation", to: "pages#estimation_v3", as: "estimation_v3"
  get "devenir-partenaire", to: "pages#partner_landing", as: "partner_landing"
  get "estimation-v2", to: "pages#estimation_v2", as: "estimation_v2"
  get "employee-model-test", to: 'pages#employee_test', as: "employee"
  get "email-job-testing", to: 'pages#email_job_testing', as: "email_job_testing"
  get "partenaires", to: "pages#partners", as: "static_partners"
  get "ajax-upload", to: "properties#ajax_photo_upload", as: "ajax_upload"
  get "conversation", to: "conversations#conversation", as: "conversation"
  post "conversation", to: "conversations#new_message", as: "conversation_message"
  get "faq", to: "pages#faq", as: "faq"

  resources :demands, only: [:create, :destroy]
  resources :sponsorships, only: [:create]
  resources :customer_advices, only: [:create]
  resources :contacts, only: [:create]
  resources :customer_questions, only: [:create]
  resources :newsletters, only: [:create]
  resources :key_facts, only: [:create]
  resources :candidacies, only: [:create]
  resources :estimations, only: [:create]
  resources :presskit_requests, only: [:create]

  resources :partners

  get "keyfact-creation", to: "key_facts#new"
  get "espace-presse", to: "pages#presse", as: "presse"
  get "chasse-immobiliere", to: "pages#hunt", as: "hunt"


  namespace :admin do
    resources :estimations, only: [:show, :index, :destroy]
    resources :press_releases, only: [:new, :show, :index, :create, :destroy, :edit, :update]

app/models/survey.rb
# frozen_string_literal: true

# class Survey
class Survey
  include Mongoid::Document
  include Mongoid::Timestamps
  embeds_one :condition, cascade_callbacks: true
  embeds_many :answers, cascade_callbacks: true

  field :position, type: Integer
  field :answer_type, type: String
  field :label_demand, type: String
  field :resume, type: String
  field :text, type: String
  field :required, type: Boolean
  field :theme, type: String
  field :comment, type: String
  field :demand_attribute, type: String
  field :active, type: Boolean
  field :checkable_on_criteria, type: Boolean
  field :client_side_condition, type: Boolean
  field :property_type, type: String

end

app/helpers/survey_helper.rb
module SurveyHelper

  def handle_keycode(keycode)
    if keycode == 49
      letter = "1"
    elsif keycode == 50
      letter = "2"
    elsif keycode == 51
      letter = "3"
    elsif keycode == 52
      letter = "4"
    elsif keycode == 53
      letter = "5"
    elsif keycode == 54
      letter = "6"
    elsif keycode == 55
      letter = "7"
    elsif keycode == 56
      letter = "8"
    elsif keycode == 57
      letter = "9"
    end
    return letter
  end

  def get_survey_input_css_class answer_type
    case answer_type
      when :radio.to_s
        input_class = 'styled-radio'
      when :checkbox.to_s
        input_class = 'styled-checkbox'
      when :text.to_s
        input_class = 'formatted-numeric-input'
      when :textarea.to_s
        input_class = 'styled-textarea'
    end
    input_class
  end

  def get_survey_input_value answer
    value = ''
    unless answer.answer_type == :textarea.to_s || answer.answer_type == :text.to_s
      value = answer.id
    end
    value
  end

  def handle_array_results(result_array)
    if result_array || result_array != []
      sanitize_array = result_array.reject{|result| (result == "") || (result == nil)}
      if sanitize_array.size == 1
        string_result = sanitize_array.first.to_s
      elsif sanitize_array.size == 2
        string_result = "#{sanitize_array.first} et #{sanitize_array.last.to_s.downcase}"
      elsif sanitize_array.size > 2
        string_result = "#{sanitize_array[0..-2].join(", ")} et #{sanitize_array.last.to_s.downcase}"
      else
        string_result = "Vous avez passez cette question"
      end
      return string_result
    else
      return "Vous avez passez cette question"
    end
  end

end

app/views/surveys/_append_user_answer.html.haml
.survey-recap-container{"data-answerposition": @last_survey.position}
  .left-content
    .survey-resume-item.hidden
      = "Q#{@last_survey.position}"
    .edit-survey-answer{"data-target": "#survey-form-#{@last_survey.position}", "data-position": @last_survey.position}
      .icon-pencil-1{style:"line-height: 1;"}
  .right-content
    .survey-recap-label
      = @last_survey.label_demand
    .survey-recap-value
      - if @demand[@last_survey.demand_attribute.to_sym].is_a?(Array)
        - if @demand[@last_survey.demand_attribute.to_sym].empty?
          = "Vous avez passé cette question"
        - @demand[@last_survey.demand_attribute.to_sym].each_with_index do |answer, index|
          - if @last_survey.answers.first.answer_type == :text.to_s && @last_survey.answers.first.text
            .survey-recap-flexbox
              .answer-title
                = "#{@last_survey.answers[index].text}"
              - if answer != ""
                = ("#{answer.gsub(',',' ')} #{@last_survey.answers.first.unit if @last_survey.answers.first.unit}")
              - else
                = "Champ non renseigné !!"
          - else
            .survey-recap-flexbox
              = answer
      - elsif @demand[@last_survey.demand_attribute.to_sym].is_a?(String)
        .survey-recap-flexbox
          - if @demand[@last_survey.demand_attribute.to_sym] == "[]"
            = "Vous avez passé cette question"
          - else
            = @demand[@last_survey.demand_attribute.to_sym]
      - else
        = "toto"
        = @demand[@last_survey.demand_attribute.to_sym].class

app/views/surveys/_final_survey.html.haml
.full-survey-container
  .container
    .resume-container
      .empty-resume
        = render 'append_user_answer'
    .questions-container
      .survey-position
        = "Q#{@survey.position}"
      = render 'survey_item'


  .modal.fade{:role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        %button{type:"button", class:"close", "data-dismiss":"modal"}
          &times
        .up-section
          %p
            %strong
              Merci pour vos réponses ! Vos choix sont tous très pertinents.
            Parfois, certains sont plus importants que d’autres, non ?
            Alors,
            %strong
              cochez les carrés pour sélectionner les 5 critères les plus importants.
            Ensuite, c’est fini pour vous ! Nous prenons le relais.
        .down-section
          = image_tag "https://cdn.bientotchezsoi-dev.com/images/modal-survey-success.jpg"
          %button.bcs-button-sm{"data-dismiss":"modal"}
            JE CHOISIS MES 5 CRITÈRES !!

  = form_tag(criterias_submit_path(demand_id: @demand.id),method: :post,id: "criterias_form") do
    .d-flex-center
      .criterias-success-title
        Je sélectionne les 5 critères les plus importants de ma recherche
    .container
      - @attributes_by_theme.each do |key, value|
        .user-results-recap-header
          = key
        .answers-container
          .row
            - value.each_with_index do |val, index|
              - if !val.last
                .col-xs-12.col-md-6
                  .answer-checkbox-container.unselectable-answer
                    .unselectable-container
                      .fa.fa-exclamation-triangle
                      .unselectable-text
                        Vous ne pouvez pas selectionner ce critère
                    .fa.fa-times-circle-o
                    .title
                      = "#{val.first} "
                    .value
                      - if val[1].is_a?(Array)
                        = handle_array_results(val[1])
                      - else
                        - if val[1] == "[]"
                          = "Vous avez passé cette question"
                        - else
                          = val[1]
              - else
                .col-xs-12.col-md-6
                  .answer-checkbox-container
                    %input.styled-checkbox{type:"checkbox",id:"#{val.first.downcase}-#{index+1}",name:"criterias[]",value:"#{val[0]}"}
                    %label{for:"#{val.first.downcase}-#{index+1}"}
                      .fa.fa-check-circle-o.checked-fa
                      .fa.fa-circle-o.unchecked-fa
                      %strong
                        = "#{val.first} "
                      .value
                        - if val[1].is_a?(Array)
                          = handle_array_results(val[1])
                        - else
                          - if val[1] == "[]"
                            = "Vous avez passé cette question"
                          - else
                            = val[1]

      .checked-input-count
        .checked-input-text
          Je sélectionne les 5 critères les plus importants de ma recherche
        = button_tag 'JE VALIDE MA DEMANDE', class: 'bcs-button-green', id: "validate-criterias"



    #modal-criterias-confirmation.custom-modal-container.hidden
      .custom-modal
        .custom-modal-closer
          .fa.fa-times
        .custom-modal-icon
          = image_tag "https://cdn.bientotchezsoi-dev.com/images/soldat-kenotte.svg", width: "120"
        .custom-modal-text-marged
          %strong
            = "Reçu 5 sur 5! Je confirme mes critères ?"
        .d-flex-center
          = link_to "Négatif, je modifie", "#", class: "bcs-button-very-small m-sides-10", id: "negative-button"
          = link_to "Affirmatif, je confirme", "#", class: "bcs-button-very-small m-sides-10", id: "affirmative-button"




= render 'stepper'

app/views/surveys/_survey_item.html.haml
= form_tag(next_survey_path, method: :post,id: "survey-form-#{@survey.position}",class: "survey-form","data-position": @survey.position) do
  = hidden_field_tag(:demand_id,@demand.id.to_s)
  = hidden_field_tag(:survey_id,@survey.id.to_s)
  = hidden_field_tag(:position,@survey.position)
  = hidden_field_tag(:theme,@survey.theme)
  = hidden_field_tag(:label_demand,@survey.label_demand)
  = hidden_field_tag(:value,@demand[@survey.demand_attribute.to_sym])
  = hidden_field_tag(:survey_count,Survey.all.size.to_i)
  = hidden_field_tag(:condition,@survey.client_side_condition)


  .survey-item
    .survey-label
      %span
      = @survey.label_demand
    .all-inputs-container
      - @survey.answers.each_with_index do |answer, index|
        - if answer.answer_type == :textarea.to_s || @survey.answer_type == :text.to_s
          = hidden_field_tag('answer_ids[]', answer.id.to_s)
          - input_name = 'answer_values[]'
        - else
          - input_name = 'answer_ids[]'
        - input_class = get_survey_input_css_class(answer.answer_type)
        - input_value = get_survey_input_value(answer)

        - if answer.answer_type == "textarea"
          .textarea-input-container
            = tag.textarea name: input_name, id: "#{@survey.position}-#{index}", class: input_class
            - if answer.text
              = tag.label answer.text, for: "#{@survey.position}-#{index}"

        - elsif answer.answer_type == "text"
          - if answer.input_width
            .input-container
              - if answer.unit
                .survey-input-absolute-hint
                  = answer.unit
              = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class, placeholder: "#{answer.text if answer.text}", maxlength: answer.limit, style: "width: #{answer.input_width};"
          - else
            .input-container
              - if answer.unit
                .survey-input-absolute-hint
                  = answer.unit
              = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class, placeholder: "#{answer.text if answer.text}", maxlength: answer.limit
        - else
          .input-container
            = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class
            - if answer.text
              = tag.label answer.text, for: "#{@survey.position}-#{index}"

        / .input-container
        /   - if answer.answer_type == "textarea"
        /     = tag.textarea name: input_name, id: "#{@survey.position}-#{index}", class: input_class
        /   - elsif answer.answer_type == "text"
        /     = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class, placeholder: "#{answer.text if answer.text}"
        /   - else
        /     = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class
        /   - if answer.unit
        /     / %span
        /     /   = answer.unit
        /   - if answer.answer_type != "text"
        /     - if answer.text
        /       = tag.label answer.text, for: "#{@survey.position}-#{index}"
    - if (@survey.answers.select{|a| a.comment}).size > 1
      .question-comment
        - @survey.answers.each do |answer|
          .question-comment-item
            = answer.comment if answer.comment
    - if @survey.comment
      .question-comment
        .question-comment-item
          = @survey.comment

    - if @survey.client_side_condition
      .budget-warning


    .buttons-container
      - if !@survey.required
        = button_tag 'JE PASSE', class: 'bcs-button-sm-light m-15', data: {passed: 1}
      = button_tag 'JE CONFIRME', class: 'bcs-button-sm hidden-btn m-15'

app/views/surveys/demand_edit.html.haml
.overflow-container
  .edit-demand-title
    Je modifie ma demande
  .full-survey-container
    .container-fullheight
      .resume-container
        - if @survey.position == 1
        - else
          = render 'append_user_answer'
      .questions-container
        = form_tag(next_survey_edit_path, method: :post,id: "survey-form-#{@survey.position}",class: "survey-form","data-position": @survey.position) do
          = hidden_field_tag(:demand_id,@demand.id.to_s)
          = hidden_field_tag(:survey_id,@survey.id.to_s)
          = hidden_field_tag(:position,@survey.position)
          = hidden_field_tag(:theme,@survey.theme)
          = hidden_field_tag(:label_demand,@survey.label_demand)
          = hidden_field_tag(:value,@demand[@survey.demand_attribute.to_sym])
          = hidden_field_tag(:survey_count,Survey.all.size.to_i)
          .survey-item
            .survey-label
              %span
              = @survey.label_demand
            .all-inputs-container
              - @survey.answers.each_with_index do |answer, index|
                - if answer.answer_type == :textarea.to_s || @survey.answer_type == :text.to_s
                  = hidden_field_tag('answer_ids[]', answer.id.to_s)
                  - input_name = 'answer_values[]'
                - else
                  - input_name = 'answer_ids[]'
                - input_class = get_survey_input_css_class(answer.answer_type)
                - input_value = get_survey_input_value(answer)

                - if answer.answer_type == "textarea"
                  .textarea-input-container
                    - if @demand[@survey.demand_attribute.to_sym] == nil
                      = tag.textarea name: input_name, id: "#{@survey.position}-#{index}", class: input_class
                    - else
                      %textarea{name: input_name, id: "#{@survey.position}-#{index}", class: input_class}
                        = @demand[@survey.demand_attribute.to_sym].last

                .input-container
                  - if (answer.answer_type == "radio") || (answer.answer_type == "checkbox") && @demand[@survey.demand_attribute.to_sym]
                    - if @demand[@survey.demand_attribute] && @demand[@survey.demand_attribute].include?(answer.text)
                      = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class, checked: true
                    - else
                      = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: input_value, class: input_class
                  - elsif answer.answer_type == "text"
                    - if @demand[@survey.demand_attribute.to_sym] == nil
                      = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", class: input_class
                    - else
                      - if index == 0
                        = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: @demand[@survey.demand_attribute.to_sym].first, class: input_class
                      - else
                        = tag.input type: answer.answer_type, name: input_name, id: "#{@survey.position}-#{index}", value: @demand[@survey.demand_attribute.to_sym].last, class: input_class
                  - if answer.unit
                    %span
                      = answer.unit
                  - if answer.text
                    = tag.label answer.text, for: "#{@survey.position}-#{index}"
            .buttons-container
              - if !@survey.required
                = button_tag 'JE PASSE', class: 'bcs-button-sm-light m-15'
              = button_tag 'JE CONFIRME', class: 'bcs-button-sm m-15'

app/views/surveys/demand_edit_final_step.html.haml
.full-survey-container
  .container
    .resume-container
      .empty-resume
        = render 'append_user_answer'
    .questions-container
      .survey-position
        = "Q#{@survey.position}"
      = render 'survey_item'


  .modal.fade{:role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        %button{type:"button", class:"close", "data-dismiss":"modal"}
          &times
        .up-section
          %p
            %strong
              Merci pour vos réponses ! Vos choix sont tous très pertinents.
            Parfois, certains sont plus importants que d’autres, non ?
            Alors,
            %strong
              cochez les carrés verts pour sélectionner les 5 critères les plus importants.
            Ensuite, c’est fini pour vous ! Nous prenons le relais.
        .down-section
          = image_tag "https://cdn.bientotchezsoi-dev.com/images/modal-survey-success.jpg"
          %button.bcs-button-sm{"data-dismiss":"modal"}
            JE CHOISIS MES 5 CRITÈRES !!

  = form_tag(criterias_submit_path(demand_id: @demand.id, edit: true),method: :post,id: "criterias_form") do
    .d-flex-center
      .criterias-success-title
        Choisissez les 5 critères les plus importants parmis vos réponses .
    .checked-input-count
      .checked-input-text
        Choisissez les 5 critères les plus importants parmis vos réponses .
      = button_tag 'JE VALIDE MA DEMANDE', class: 'bcs-button-green', id: "validate-criterias"
    .container
      - @attributes_by_theme.each do |key, value|
        .user-results-recap-header
          = key
        .answers-container
          .row
            - value.each_with_index do |val, index|
              - if !val.last
                .col-xs-12.col-md-6
                  .answer-checkbox-container.unselectable-answer
                    .unselectable-container
                      .fa.fa-exclamation-triangle
                      .unselectable-text
                        Vous ne pouvez pas selectionner ce critère
                    .fa.fa-times-circle-o
                    .title
                      = "#{val.first} : "
                    .value
                      - if val[1].is_a?(Array)
                        = val[1].first
                      - else
                        = val[1]
              - else
                .col-xs-12.col-md-6
                  .answer-checkbox-container
                    - if @demand.important_fields
                      - if @demand.important_fields.include?(val.first.capitalize) || @demand.important_fields.include?(val.first.upcase)
                        %input.styled-checkbox{type:"checkbox",id:"#{val.first.downcase}-#{index+1}",name:"criterias[]",value:"#{val[0]}", checked: true}
                        %label{for:"#{val.first.downcase}-#{index+1}"}
                          .fa.fa-check-circle-o.checked-fa
                          .fa.fa-circle-o.unchecked-fa
                          %strong
                            = "#{val.first} : "
                          .value
                            - if val[1].is_a?(Array)
                              = val[1].first
                            - else
                              = val[1]
                      - else
                        %input.styled-checkbox{type:"checkbox",id:"#{val.first.downcase}-#{index+1}",name:"criterias[]",value:"#{val[0]}"}
                        %label{for:"#{val.first.downcase}-#{index+1}"}
                          %strong
                            = "#{val.first} : "
                          .value
                            - if val[1].is_a?(Array)
                              = val[1].first
                            - else
                              = val[1]


    #modal-criterias-confirmation.custom-modal-container.hidden
      .custom-modal
        .custom-modal-closer
          .fa.fa-times
        .custom-modal-icon
          = image_tag "https://cdn.bientotchezsoi-dev.com/images/soldat-kenotte.svg", width: "120"
        .custom-modal-text-marged
          %strong
            = "Reçu 5 sur 5! Je confirme mes critères ?"
        .d-flex-center
          = link_to "Négatif, je modifie", "#", class: "bcs-button-very-small m-sides-10", id: "negative-button"
          = link_to "Affirmatif, je confirme", "#", class: "bcs-button-very-small m-sides-10", id: "affirmative-button"