config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  root to: 'v4/pages#home_v4'

  mount ActionCable.server => '/cable'
  # handle websocket for messagerie
  resources :chatrooms
  resources :chat_messages
  resources :customer_requests, only: [:create]

  # Api version of bcs
  namespace :api do
    namespace :agency do
      resources :agencies, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "agencies#status"
    end
    namespace :customer do
      resources :customers, only: [:show]
      post 'authenticate', to: 'authentication#authenticate'
      get 'status', to: "customers#status"
    end
  end

  namespace :rent do
    resources :agencies
  end

  namespace :apifluxes do
    resources :properties
    resources :agencies
    post "activate_agency_flux_recovery/:id", to: "agencies#activate_agency_flux_recovery", as: "activate_flux"
  end

  post 'activate_rent_agency', to: "rent/agencies#activate"
  post 'deactivate_rent_agency', to: "rent/agencies#deactivate"

  get 'widgets/:id/:template/', to: 'widgets#show'
  get 'widgets/iframe_version', to: 'widgets#iframe_version'

  get "estimations/new_estimation", to: "estimations#new_estimation", as: "new_estimation"

  get "sending_sms", to: "phone_messages#sending_sms", as: "sending_sms"
  get "change_property_status/:id", to: "properties#change_status", as: "change_status"


  namespace :webhooks do
    post "releases", to: "heroku#releases", as: "releases"
    post "builds", to: "heroku#builds", as: "builds"
    post "app", to: "heroku#app", as: "app"
    post "submit", to: "typeform#submit", as: "submit"
    post "sent", to: "mandrill#sent", as: "sent"
    post "open", to: "mandrill#open", as: "open"
    post "click", to: "mandrill#click", as: "click"
    post "build", to: "codeship#build", as: "build"
    post "delivery", to: "nexmo#delivery", as: "delivery"
    post "malab/submit", to: "malab#submit", as: "malab_submit"
    get "malab_view", to: "pages#malab_view", as: "malab_view"
    get "sent", to: "mandrill#sent"
    get "open", to: "mandrill#open"
    get "click", to: "mandrill#click"
    get "list", to: "pages#list", as: "list"
    get "typeform_list", to: "pages#typeform_list", as: "typeform_list"
    get "visits", to: "pages#visits", as: "visits"
    post "survey", to: "aristid#survey", as: "survey"
    get "aristid/test", to: "aristid#test", as: "aristid_test"
    get "aristid/initial_request", to: "aristid#initial_request"
    post "aristid/initial_request", to: "aristid#initial_request", as: "initial_request"
  end


  namespace :analytics do
    get "demands", to: "demands#index", as: "demands"
    get "demands/:id", to: "demands#show", as: "demand"
  end

  namespace :v4 do
    get "new-home", to: "pages#home_v4", as: "home_v4"
    get "matching_algo_test", to: "pages#matching_algo_test", as: "matching_algo_test"
  end

  namespace :typeform do
    get "advanced_input_return", to: "rents#advanced_input_return", as: "advanced_input_return"
    get "advanced_input", to: "rents#advanced_input", as: "advanced_input"
    get "responses", to: "rents#responses", as: "responses"
    get "mail_response", to: "rents#mail_response", as: "mail_response"
    get "persisted_typeforms", to: "rents#persisted_typeforms", as: "persisted_typeforms"
    get "mailer_test", to: "rents#mailer_test", as: "mailer_test"
  end

  namespace :access do
    resources :properties
    get "success", to: "properties#success", as: "success"
    get "service_test", to: "properties#service_test", as: "service_test"
    get "budget_script", to: "properties#handle_demands_budget_to_integer", as: "budget_script"
    get "new_mailer", to: "properties#all_offers_without_choice", as: "new_mailer"
  end

  namespace :v2 do
    get "test_api_connect", to: "pages#test_api_connect", as: 'test_api_connect'
    resources :v2_demands
    get "results", to: "v2_demands#results", as: "results"
    get "ajax_query", to: "v2_demands#influence_ajax_query", as: "influence_ajax_query"

    get "pdf", to: "pdfs#show", as: "pdf"
    get "demand-stats", to: "pages#demand_stats", as: "demand_stats"
    get "migrations", to: "pages#migrations", as: "migrations"
    get "new-survey", to: "pages#new_survey", as: "new_survey"
    post "next-question", to: "pages#next_question", as: "next_survey_v2"
    post "last-question", to: "pages#last_question", as: "last_survey_v2"
    post "next-question-on-skip", to: "pages#next_question_on_skip", as: "next_survey_on_skip"
    get "demand-view", to: "pages#demand_view", as: "demand_view"
    post "orderable", to: "pages#orderable", as: "survey_orderable"
    post "new-question", to: "pages#new_question", as: "new_question"
    get "test-new-survey", to: "pages#test_new_survey", as: "test_new_survey"
    post "test-next-question", to: "pages#test_next_question", as: "test_next_question"
    post "criterias-v2", to: "pages#criterias", as: "criterias_v2"
    get "summary", to: "pages#summary", as: "summary"
    get "map", to: "pages#map", as: "map"
    get "start", to: "pages#start", as: "start"
    post "multi_circle_batch_constructor", to: "pages#multi_circle_batch_constructor", as: "mcbc"
    get "dashboard", to: "customers#home", as: "old_customer_dashboard"
    resources :questions, only: [:edit, :update]
    resources :sentences, only: [:edit, :update]
    resources :v2_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :v2_answers, only: [:new, :create, :edit, :update]
    get "week_stats", to: "statistics#week_stats", as: "week_stats"

    # Arthur routing
    get "dashboard/agency/home", to: "agencies#home", as: "agency_dashboard"
    get "dashboard/agency/props_waiting_for_choice", to: "agencies#props_waiting_for_choice", as: "props_waiting_for_choice"
    get "dashboard/agency/demands", to: "agencies#demands", as: "dashboard_agency_demands"
    get "dashboard/agency/properties", to: "agencies#properties", as: "dashboard_agency_properties"
    get "bcs-property-show", to: "agencies#property_show", as: "bcs_property_show"
    get "dashboard/agency/pending_offers", to: "agencies#pending_offers", as: "dashboard_agency_pending_offers"
    get 'dashboard/agency/demand/:demand_id', to: "agencies#demand", as: "dashboard_agency_demand"
    post "dashboard/agency/demands/search_with_ajax", to: "agencies#search_with_ajax", as: "dashboard_agency_demands_search_with_ajax"

    get "ajaxified_customer_choice", to: "customer_choices#customer_choice_ajax", as: "ajaxified_choices"

    # New customer dashboard routing
    get "dashboard/customer/home", to: "customers#home", as: "customer_dashboard"
    get "dashboard/customer/mes_petits_plus", to: "customers#my_little_mores", as: "mores"
    get "dashboard/customer/advices", to: "customers#advices", as: "advices"
    get "dashboard/customer/journey", to: "customers#journey", as: "journey"
    get "dashboard/customer/selection", to: "customers#selection", as: "selection"
    get "dashboard/customer/properties", to: "customers#properties", as: "customer_dashboard_properties"
    get "dashboard/customer/properties/:property_id", to: "customers#property", as: "customer_dashboard_property"
    get "dashboard/customer/messages", to: "customers#messages", as: "customer_dashboard_messages"
    post "dashboard/customer/properties/:property_id/hate", to: "customer_choices#hate", as: "customer_choice_hate"
    post "dashboard/customer/properties/:property_id/like", to: "customer_choices#like", as: "customer_choice_like"
    post "dashboard/customer/properties/customer_unlike_choice_ajax", to: "customers#customer_unlike_choice_ajax", as: "customer_dashboard_properties_customer_unlike_choice_ajax"
    post "dashboard/customer/properties/customer_like_choice_ajax", to: "customers#customer_like_choice_ajax", as: "customer_dashboard_properties_customer_like_choice_ajax"

  end

  get "s3_migration", to: "pages#s3_to_cloudinary_migration", as: "s3_migration"
  get "s3_migration_for_hektor", to: "pages#s3_migration_for_hektor_flux", as: "s3_hektor_migration"

  get "test_unviewed_demands_mailing", to: "pages#test_unviewed_demands_mailing", as: "mailing_test"
  get "dico-de-kenotte", to: "pages#glossary", as: "glossary"
  get "bcs-properties", to: "pages#bcs_properties", as: "exclu_bcs_properties"
  get "bcs-property-show", to: "pages#bcs_property_show", as: "home_bcs_property_show"
  get "estimation", to: "pages#estimation_v3", as: "estimation_v3"
  get "devenir-partenaire", to: "pages#partner_landing", as: "partner_landing"
  get "estimation-v2", to: "pages#estimation_v2", as: "estimation_v2"
  get "employee-model-test", to: 'pages#employee_test', as: "employee"
  get "email-job-testing", to: 'pages#email_job_testing', as: "email_job_testing"
  get "partenaires", to: "pages#partners", as: "static_partners"
  get "ajax-upload", to: "properties#ajax_photo_upload", as: "ajax_upload"
  get "conversation", to: "conversations#conversation", as: "conversation"
  post "conversation", to: "conversations#new_message", as: "conversation_message"
  get "faq", to: "pages#faq", as: "faq"

  resources :demands, only: [:create, :destroy]
  resources :sponsorships, only: [:create]
  resources :customer_advices, only: [:create]
  resources :contacts, only: [:create]
  resources :customer_questions, only: [:create]
  resources :newsletters, only: [:create]
  resources :key_facts, only: [:create]
  resources :candidacies, only: [:create]
  resources :estimations, only: [:create]
  resources :presskit_requests, only: [:create]

  resources :partners

  get "keyfact-creation", to: "key_facts#new"
  get "espace-presse", to: "pages#presse", as: "presse"
  get "chasse-immobiliere", to: "pages#hunt", as: "hunt"


  namespace :admin do
    resources :estimations, only: [:show, :index, :destroy]
    resources :press_releases, only: [:new, :show, :index, :create, :destroy, :edit, :update]

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  http_basic_authenticate_with name: ENV["HTTP_AUTH_LOGIN"], password: ENV["HTTP_AUTH_PWD"]



  def generate_xls_file
    if params[:collection]
      if params[:collection] == "activated"
        @customers = Customer.all.select{|customer| customer.valid?}
        @filename = "active-customers"
      elsif params[:collection] == "uncompleted"
        @customers = Customer.all.reject{|customer| customer.valid?}
        @filename = "uncompleted-customers"
      end
    end
    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename='#{@filename}.xlsx'"
      }
    end
  end



  def index
    @valid_customers = Customer.where(email: {'$ne': ""})
    @unvalid_customers = Customer.where(email: {'$eq': ""})
    render "admin/customers/index", layout: "admin"
  end

  def valid
    @valid_customers = Customer.where(email: {'$ne': ""}).order_by(created_at: :desc).page params[:page]
    render "admin/customers/valid", layout: "admin"
  end

  def unvalid
    @unvalid_customers = Customer.where(email: {'$eq': ""}).order_by(created_at: :desc).page params[:page]
    render "admin/customers/unvalid", layout: "admin"
  end

  def show
    @customer = Customer.find(params[:id])
    @customers = Customer.all
    @demands = Demand.all
    @agencies = Agency.all
    @properties = Property.all.limit(200)
    @sponsorships = Sponsorship.all
    @estimations = Estimation.all.where(contact_require: true)
    @press_releases = PressRelease.all
    @presskit_requests = PresskitRequest.all
    @pages = Page.all
    render "admin/customers/show", layout: "admin"
  end

  def edit
    @customer = Customer.find(params[:id])
    render "admin/customers/edit", layout: "admin"
  end

  def update
    @customer = Customer.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:id].to_s)
    @customer.destroy
    redirect_to admin_valid_customers_path, notice: "Utilisateur effacé"
  end

end

app/controllers/api/customer/authentication_controller.rb
class Api::Customer::AuthenticationController < Api::Customer::BaseController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_customer_request

  def authenticate
    set_api_authenticate_at
    command = AuthenticateCustomer.call(params[:email], params[:password])
    if command.success?
      puts command.result
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end

  private

  def set_api_authenticate_at
    if params[:email] && params[:password]
      email = params[:email]
      password = params[:password]
      @customer = Customer.find_by(email: params[:email])
      if @customer && Customer.authenticate(email,password)
        @customer.last_api_authenticate_at = Time.now
        @customer.save(validate: false)
      end
    end
  end

end

app/controllers/api/customer/base_controller.rb
class Api::Customer::BaseController < ApplicationController
  before_action :authenticate_customer_request
  attr_reader :current_customer

  private

  def authenticate_customer_request
    @current_customer = AuthorizeCustomerApiRequest.call(request.headers).result
    render json: { error: 'Not Authorized' }, status: 401 unless @current_customer
  end

end

app/controllers/api/customer/customers_controller.rb
class Api::Customer::CustomersController < Api::Customer::BaseController

  def show
    if current_customer
      puts '---- Inside show action (Customer) ----'
    end
    render json: {resource: "customer", object: current_customer}
  end

  def status
    if current_customer
      puts '---- Inside status action (Customer) ----'
    end
    render json: {status: "connected", last_authenticate_at: "#{current_customer.last_api_authenticate_at}", email: current_customer.email}.as_json, status: :ok
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:dashboard]

  def dashboard
    if session[:bcs_customer_id]
      @temporary_customer = Customer.find(session[:bcs_customer_id])
      @demand = @temporary_customer.demands.last.clone
      @customer = current_customer
      @customer.demands.push(@demand)
      @reward = Reward.new(badge: "Chaton timide", score: 50)
      @customer.rewards.push(@reward)
      @demand.completed = true
      @demand.save
      @customer.save
      @label_test = test_on_label(@demand)
      (@labels = find_formatted_survey_label(@demand)) if @demand
      @temporary_customer.destroy if @temporary_customer
      session.delete(:bcs_customer_id)
    else
      @customer = current_customer
      if !@customer.rewards.any?
        @reward = Reward.new(badge: "Chaton timide", score: 50)
        @customer.rewards.push(@reward)
      end
      @customer.save
      @demand = @customer.demands.last
      (@label_test = test_on_label(@demand)) if @demand
      (@labels = find_formatted_survey_label(@demand)) if @demand
    end
    if @customer.sign_in_count < 2
      # CustomerMailer.welcome.deliver_now
    end
    @customer_adapted_blog_post = Post.all.where(name: "Avant / après la visite d’un bien : le mémo !").last
    render "dashboard/connected/dashboard"
  end

  private

  def find_formatted_survey_label(demand)
    labels = []
    demand.attributes.each do |attr|
      survey = Survey.where(demand_attribute: attr.first.to_s).last
      (labels << survey.resume) if survey
    end
    labels
  end

  def test_on_label(demand)
    labels = []
    @demand_filter = demand.attributes.map{|attr| attr if (attr != nil || attr != "")}
    @demand_filter.each do |attribute|
      labels << attribute
    end
    labels
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/helpers/customer_helper.rb
module CustomerHelper

  def reward_picture(score)
    if score == 0
      @photo_url = "https://cdn.bientotchezsoi-dev.com/images/rank-fox.svg"
    elsif score == 50
      @photo_url = "https://cdn.bientotchezsoi-dev.com/images/rank-cat.svg"
    elsif score == 100
      @photo_url = "https://cdn.bientotchezsoi-dev.com/images/rank-kenotte.svg"
    elsif score == 150
      @photo_url = "https://cdn.bientotchezsoi-dev.com/images/rank-rabbit.svg"
    end
    return @photo_url
  end

end

app/views/dashboard/customers/partials/_advices.html.haml
.agency-dashboard-fullpage
  = render "dashboard/customers/partials/fixed_menu"

  .dashboard-fullpage-container

    .d-flex-center
      %h2.bold LES CONSEILS DE KENOTTE

    %div
      .row
        - @target_posts.sort_by{|post| post.created_at}.reverse.each do |post|
          .col-xs-12.col-md-6
            .blog-card.shadowed.card-margin
              .top-section{style:"background-image: url('#{post.photo_url}');"}
                = link_to post_path(cat_lname: post.blog_category.lname, lname: post.lname), target: "_blank" do
                  .absolute-layout
                    .plus-logo
                      +
              .bottom-section
                %h4
                  = post.name
                .d-flex-start
                  %small
                    = "#{l(post.created_at, format: :medium)} |"
                  %small.card-category
                    = post.category_name.capitalize
                %p
                  - if post.title
                    = post.title.truncate(80)
                  - else
                    = post.content.truncate(80).html_safe
                = link_to "Lire la suite", post_path(cat_lname: post.blog_category.lname, lname: post.lname), class: "blog-card-link"

app/views/dashboard/customers/partials/_fixed_menu.html.haml
.customer-fixed-menu-container
  .customer-fixed-menu
    = link_to customer_zone_path, class: "#{'active' if current_page?(customer_zone_path)}" do
      .menu-picto-container
        - if current_page?(customer_zone_path)
          .inline-svg.red
            = svg("dashboard")
        - else
          .inline-svg.black
            = svg("dashboard")
        .picto-container-text
          MON ESPACE

    - if @customer.demands.any? && @customer.demands.last.properties.any?
      = link_to dashboard_customer_properties_path, class: "#{'active' if current_page?(dashboard_customer_properties_path)}" do
        .menu-picto-container
          - if current_page?(dashboard_customer_properties_path)
            .inline-svg.red
              = svg("heart")
          - else
            .inline-svg.black
              = svg("heart")
          .picto-container-text
            MES OFFRES
    - if @customer.demands.any?
      = link_to dashboard_customer_partnerships_path, class: "#{'active' if current_page?(dashboard_customer_partnerships_path)}" do
        .menu-picto-container
          - if current_page?(dashboard_customer_partnerships_path)
            .inline-svg.red
              = svg("hand-peace")
          - else
            .inline-svg.black
              = svg("hand-peace")
          .picto-container-text
            PARTENARIATS

    = link_to dashboard_customer_advices_path, class: "#{'active' if current_page?(dashboard_customer_advices_path)}" do
      .menu-picto-container
        - if current_page?(dashboard_customer_advices_path)
          .inline-svg.red
            = svg("tete-castor")
        - else
          .inline-svg.black
            = svg("tete-castor")
        .picto-container-text
          MES CONSEILS

    = link_to dashboard_customer_messages_path, class: "#{'active' if current_page?(dashboard_customer_messages_path)}" do
      .menu-picto-container
        - if current_page?(dashboard_customer_messages_path)
          .inline-svg.red
            = svg("message-comment")
        - else
          .inline-svg.black
            = svg("message-comment")
        .picto-container-text
          MA MESSAGERIE

    = link_to edit_customer_registration_path, class: "#{'active' if current_page?(dashboard_customer_profil_path)}" do
      .menu-picto-container
        - if current_page?(dashboard_customer_profil_path)
          .inline-svg.red
            = svg("user-infos")
        - else
          .inline-svg.black
            = svg("user-infos")
        .picto-container-text
          MON PROFIL

app/views/dashboard/customers/partials/_messages.html.haml
.agency-dashboard-fullpage
  = render "dashboard/customers/partials/fixed_menu"

  .dashboard-fullpage-container
    .big-header
      .demand-number MA MESSAGERIE
      .d-flex-start
        %p
          Je contacte les agences qui possèdent les biens qui me plaisent


    .dashboard-messages-container
      - if @customer_chatrooms != []
        - @customer_chatrooms.each do |chatroom|
          - unseen_messages = chatroom.chat_messages.where(seen_by_customer: false)
          - customer_choice = chatroom.property.customer_choices.where(v2_demand_id: chatroom.v2_demand.id).last
          .dashboard-message-card
            - if unseen_messages != []
              .message-card-avatar-with-image.active{style: "background-image: url('https://s3.eu-west-3.amazonaws.com/bientotchezsoi/svgs/chatroom/chatroom-agency-avatar.svg');"}
                .fa.fa-user
                .message-count
                  = "#{unseen_messages.count}"
            - else
              .message-card-avatar-with-image{style: "background-image: url('https://s3.eu-west-3.amazonaws.com/bientotchezsoi/svgs/chatroom/chatroom-agency-avatar.svg');"}
                .fa.fa-user
            .message-card-customer
              - if customer_choice
                = "#{chatroom.agency.name}"
              - else
                = "L'agence"
            .message-delimiter
            .message-card-prop
              = "#{chatroom.property.property_type}, #{chatroom.property.price} €"
            .message-card-title
              = chatroom.topic.truncate(40)

            .grow-button-container
              - if unseen_messages != []
                = link_to chatroom_path(chatroom, property_id: chatroom.property.id.to_s) do
                  .message-card-button.active Je réponds
              - else
                = link_to chatroom_path(chatroom, property_id: chatroom.property.id.to_s) do
                  .message-card-button Je consulte

app/views/dashboard/customers/partials/_partnerships.html.haml
.services-banner{style: "background-image: url(https://cdn.bientotchezsoi-dev.com/images/placeholders/services-banner-photo.jpg);"}
  .content
    %h1.white-text des travaux en vue ?

.agency-dashboard-fullpage
  = render "dashboard/customers/partials/fixed_menu"
  .dashboard-fullpage-container
    .container-inactive
      .row
        .col-xs-12
          .header
            %h2.bold
              des partenaires professionnels et fiables
        - @partners.each do |partner|
          - if partner.technology.downcase == "lien classique"
            .col-xs-12.col-md-6
              .customer-service-card
                - if partner.logo_url
                  .d-flex-center
                    = image_tag partner.logo_url, width: "160"
                .d-flex-start.mt-20
                  .service-truncate-content
                    = partner.content.truncate(240)
                .d-flex-center.mt-20
                  = link_to partner.service_url, target: "_blank" do
                    .bold.green-text
                      = "Je découvre le service"
          - else
            .col-xs-12.col-md-6
              .customer-service-card
                - if partner.logo_url
                  .d-flex-center
                    - if partner.name.downcase == "bon de visite"
                      = image_tag partner.logo_url, width: "100"
                    - else
                      = image_tag partner.logo_url, width: "160"
                .d-flex-start.mt-20
                  .service-truncate-content
                    = partner.content.truncate(240)
                .d-flex-center.mt-20
                  .bold.green-text.widget-service-link{"data-toggle": "modal", "data-target": "#customer-services", "data-url-target": "#{partner.id.to_s}"}
                    = "Je commence"
            %script{src: "#{partner.widget_url}", type: "text/javascript"}




#customer-services.modal.fade{role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-body.dynamic-receiver

app/views/dashboard/customers/partials/_vip_advices.html.haml
.agency-dashboard-fullpage
  = render "dashboard/customers/partials/vip_fixed_menu"

  .dashboard-fullpage-container.vip

    .d-flex-center
      %h2.header-vip.bold Mes conseils personnalisés

    %div
      .row
        - @target_posts.sort_by{|post| post.created_at}.reverse.each do |post|
          .col-xs-12.col-md-6
            .blog-card.vip.card-margin
              .top-section{style:"background-image: url('#{post.photo_url}');"}
                = link_to post_path(cat_lname: post.blog_category.lname, lname: post.lname), target: "_blank" do
                  .absolute-layout
                    .plus-logo
                      +
              .bottom-section
                %h4
                  = post.name
                .d-flex-start
                  %small
                    = "#{l(post.created_at, format: :medium)} |"
                  %small.card-category
                    = post.category_name.capitalize
                %p
                  - if post.title
                    = post.title.truncate(80)
                  - else
                    = post.content.truncate(80).html_safe
                = link_to "Lire la suite", post_path(cat_lname: post.blog_category.lname, lname: post.lname), class: "blog-card-link"

app/views/dashboard/customers/partials/_vip_fixed_menu.html.haml
.customer-fixed-menu-container.vip
  .customer-fixed-menu
    = link_to customer_zone_path, class: "#{'active' if current_page?(customer_zone_path)}" do
      .menu-picto-container
        .inline-svg.black
          = svg("dashboard")
        .picto-container-text
          MON ESPACE
    - if @customer.demands.any? && @customer.demands.last.properties.any?
      = link_to dashboard_customer_properties_path, class: "#{'active' if current_page?(dashboard_customer_properties_path)}" do
        .menu-picto-container
          .inline-svg.black
            = svg("heart")
          .picto-container-text
            MES OFFRES
    = link_to dashboard_customer_advices_path, class: "#{'active' if current_page?(dashboard_customer_advices_path)}" do
      .menu-picto-container
        .inline-svg.black
          = svg("tete-castor")
        .picto-container-text
          MES CONSEILS

    - if current_customer.vip
      = link_to dashboard_customer_vip_path, class: "#{'active' if current_page?(dashboard_customer_vip_path)}" do
        .menu-picto-container
          .inline-svg.black
            = svg("hand-peace")
          .picto-container-text
            MES AVANTAGES VIP

    = link_to edit_customer_registration_path, class: "#{'active' if current_page?(dashboard_customer_profil_path)}" do
      .menu-picto-container
        .inline-svg.black
          = svg("user-infos")
        .picto-container-text
          MON PROFIL