config/routes.rb
    post "sent", to: "mandrill#sent", as: "sent"
    post "open", to: "mandrill#open", as: "open"
    post "click", to: "mandrill#click", as: "click"
    post "build", to: "codeship#build", as: "build"
    post "delivery", to: "nexmo#delivery", as: "delivery"
    post "malab/submit", to: "malab#submit", as: "malab_submit"
    get "malab_view", to: "pages#malab_view", as: "malab_view"
    get "sent", to: "mandrill#sent"
    get "open", to: "mandrill#open"
    get "click", to: "mandrill#click"
    get "list", to: "pages#list", as: "list"
    get "typeform_list", to: "pages#typeform_list", as: "typeform_list"
    get "visits", to: "pages#visits", as: "visits"
    post "survey", to: "aristid#survey", as: "survey"
    get "aristid/test", to: "aristid#test", as: "aristid_test"
    get "aristid/initial_request", to: "aristid#initial_request"
    post "aristid/initial_request", to: "aristid#initial_request", as: "initial_request"
  end


  namespace :analytics do
    get "demands", to: "demands#index", as: "demands"
    get "demands/:id", to: "demands#show", as: "demand"
  end

  namespace :v4 do
    get "new-home", to: "pages#home_v4", as: "home_v4"
    get "matching_algo_test", to: "pages#matching_algo_test", as: "matching_algo_test"
  end

  namespace :typeform do
    get "advanced_input_return", to: "rents#advanced_input_return", as: "advanced_input_return"
    get "advanced_input", to: "rents#advanced_input", as: "advanced_input"
    get "responses", to: "rents#responses", as: "responses"
    get "mail_response", to: "rents#mail_response", as: "mail_response"
    get "persisted_typeforms", to: "rents#persisted_typeforms", as: "persisted_typeforms"
    get "mailer_test", to: "rents#mailer_test", as: "mailer_test"
  end

  namespace :access do
    resources :properties
    get "success", to: "properties#success", as: "success"
    get "service_test", to: "properties#service_test", as: "service_test"
    get "budget_script", to: "properties#handle_demands_budget_to_integer", as: "budget_script"
    get "new_mailer", to: "properties#all_offers_without_choice", as: "new_mailer"
  end

  namespace :v2 do
    get "test_api_connect", to: "pages#test_api_connect", as: 'test_api_connect'
    resources :v2_demands
    get "results", to: "v2_demands#results", as: "results"
    get "ajax_query", to: "v2_demands#influence_ajax_query", as: "influence_ajax_query"

    get "pdf", to: "pdfs#show", as: "pdf"
    get "demand-stats", to: "pages#demand_stats", as: "demand_stats"
    get "migrations", to: "pages#migrations", as: "migrations"
    get "new-survey", to: "pages#new_survey", as: "new_survey"
    post "next-question", to: "pages#next_question", as: "next_survey_v2"
    post "last-question", to: "pages#last_question", as: "last_survey_v2"
    post "next-question-on-skip", to: "pages#next_question_on_skip", as: "next_survey_on_skip"
    get "demand-view", to: "pages#demand_view", as: "demand_view"
    post "orderable", to: "pages#orderable", as: "survey_orderable"
    post "new-question", to: "pages#new_question", as: "new_question"
    get "test-new-survey", to: "pages#test_new_survey", as: "test_new_survey"
    post "test-next-question", to: "pages#test_next_question", as: "test_next_question"
    post "criterias-v2", to: "pages#criterias", as: "criterias_v2"
    get "summary", to: "pages#summary", as: "summary"
    get "map", to: "pages#map", as: "map"
    get "start", to: "pages#start", as: "start"
    post "multi_circle_batch_constructor", to: "pages#multi_circle_batch_constructor", as: "mcbc"
    get "dashboard", to: "customers#home", as: "old_customer_dashboard"
    resources :questions, only: [:edit, :update]
    resources :sentences, only: [:edit, :update]
    resources :v2_conditions, only: [:new, :create, :edit, :update, :destroy]
    resources :v2_answers, only: [:new, :create, :edit, :update]
    get "week_stats", to: "statistics#week_stats", as: "week_stats"

    # Arthur routing
    get "dashboard/agency/home", to: "agencies#home", as: "agency_dashboard"
    get "dashboard/agency/props_waiting_for_choice", to: "agencies#props_waiting_for_choice", as: "props_waiting_for_choice"
    get "dashboard/agency/demands", to: "agencies#demands", as: "dashboard_agency_demands"
    get "dashboard/agency/properties", to: "agencies#properties", as: "dashboard_agency_properties"
    get "bcs-property-show", to: "agencies#property_show", as: "bcs_property_show"
    get "dashboard/agency/pending_offers", to: "agencies#pending_offers", as: "dashboard_agency_pending_offers"
    get 'dashboard/agency/demand/:demand_id', to: "agencies#demand", as: "dashboard_agency_demand"
    post "dashboard/agency/demands/search_with_ajax", to: "agencies#search_with_ajax", as: "dashboard_agency_demands_search_with_ajax"

    get "ajaxified_customer_choice", to: "customer_choices#customer_choice_ajax", as: "ajaxified_choices"

    # New customer dashboard routing
    get "dashboard/customer/home", to: "customers#home", as: "customer_dashboard"
    get "dashboard/customer/mes_petits_plus", to: "customers#my_little_mores", as: "mores"
    get "dashboard/customer/advices", to: "customers#advices", as: "advices"
    get "dashboard/customer/journey", to: "customers#journey", as: "journey"
    get "dashboard/customer/selection", to: "customers#selection", as: "selection"
    get "dashboard/customer/properties", to: "customers#properties", as: "customer_dashboard_properties"
    get "dashboard/customer/properties/:property_id", to: "customers#property", as: "customer_dashboard_property"
    get "dashboard/customer/messages", to: "customers#messages", as: "customer_dashboard_messages"
    post "dashboard/customer/properties/:property_id/hate", to: "customer_choices#hate", as: "customer_choice_hate"
    post "dashboard/customer/properties/:property_id/like", to: "customer_choices#like", as: "customer_choice_like"
    post "dashboard/customer/properties/customer_unlike_choice_ajax", to: "customers#customer_unlike_choice_ajax", as: "customer_dashboard_properties_customer_unlike_choice_ajax"
    post "dashboard/customer/properties/customer_like_choice_ajax", to: "customers#customer_like_choice_ajax", as: "customer_dashboard_properties_customer_like_choice_ajax"

  end

  get "s3_migration", to: "pages#s3_to_cloudinary_migration", as: "s3_migration"
  get "s3_migration_for_hektor", to: "pages#s3_migration_for_hektor_flux", as: "s3_hektor_migration"

  get "test_unviewed_demands_mailing", to: "pages#test_unviewed_demands_mailing", as: "mailing_test"
  get "dico-de-kenotte", to: "pages#glossary", as: "glossary"
  get "bcs-properties", to: "pages#bcs_properties", as: "exclu_bcs_properties"
  get "bcs-property-show", to: "pages#bcs_property_show", as: "home_bcs_property_show"
  get "estimation", to: "pages#estimation_v3", as: "estimation_v3"
  get "devenir-partenaire", to: "pages#partner_landing", as: "partner_landing"
  get "estimation-v2", to: "pages#estimation_v2", as: "estimation_v2"
  get "employee-model-test", to: 'pages#employee_test', as: "employee"
  get "email-job-testing", to: 'pages#email_job_testing', as: "email_job_testing"
  get "partenaires", to: "pages#partners", as: "static_partners"
  get "ajax-upload", to: "properties#ajax_photo_upload", as: "ajax_upload"
  get "conversation", to: "conversations#conversation", as: "conversation"
  post "conversation", to: "conversations#new_message", as: "conversation_message"
  get "faq", to: "pages#faq", as: "faq"

  resources :demands, only: [:create, :destroy]
  resources :sponsorships, only: [:create]
  resources :customer_advices, only: [:create]
  resources :contacts, only: [:create]
  resources :customer_questions, only: [:create]
  resources :newsletters, only: [:create]
  resources :key_facts, only: [:create]
  resources :candidacies, only: [:create]
  resources :estimations, only: [:create]
  resources :presskit_requests, only: [:create]

  resources :partners

  get "keyfact-creation", to: "key_facts#new"
  get "espace-presse", to: "pages#presse", as: "presse"
  get "chasse-immobiliere", to: "pages#hunt", as: "hunt"


  namespace :admin do
    resources :estimations, only: [:show, :index, :destroy]
    resources :press_releases, only: [:new, :show, :index, :create, :destroy, :edit, :update]
    resources :presskit_requests, only: [:show, :index, :destroy]
    resources :pages
    resources :posts
    resources :demand_comments
    resources :v2_demand_comments
    resources :suggestions
    patch "demands/:id", to: "demands#update", as: "v2_demand"
    get "refused-demand", to: "demands#refused_demand", as: "refused_demand"
    get "deactivated-demand", to: "demands#deactivate_demand", as: "deactivate_demand"
    get "deactivated-demand-with-message", to: "demands#deactivated_with_message", as: "deactivated_with_message"
    patch "deactivated-edit", to: "demands#deactivate_demand_with_message", as: "deactivated_demand_with_message"
  end

  resources :press_releases, only: [:show]


  get "errors/404", to: "errors#not_found", as: "not_found"

  get "estimation/resultat/:estimation_id", to: "estimations#result", as: "estimation_result"
  patch "estimation/finish/:estimation_id", to: "estimations#update", as: "estimation_update"

  post 'dashboard/customer/property/hate', to: "customer_choices#hate", as: "customer_choice_hate"
  post 'dashboard/customer/property/like', to: "customer_choices#like", as: "customer_choice_like"
  post 'dashboard/customer/property/love', to: "customer_choices#love", as: "customer_choice_love"

  get 'dashboard/customer/property-like', to: "customer_advices#create", as: "dashboard_customer_likes"
  get 'dashboard/customer/new-advice', to: "customer_advices#new", as: "dashboard_customer_new_advice"


  get 'dashboard/customer/messages', to: "dashboard/customers#messages", as: "dashboard_customer_messages"


  get 'dashboard/customer/home', to: "dashboard/customers#home", as: 'customer_zone'

app/controllers/maps_controller.rb
require 'rest-client'

class MapsController < ApplicationController

  def map
    if customer_signed_in? && current_customer.demands.any?
      @customer_adapted_blog_post = Post.all.where(name: "Avant / après la visite d’un bien : le mémo !").last
      gon.push({
        lat: 44.836151,
        lng: -0.580816,
        origin: "restricted",
        city: "Bordeaux"
      })
      render "map/restricted_demand_map", layout: 'map'
    else
      create_empty_demand
      gon.push({
        lat: params[:lat],
        lng: params[:lng],
        city: params[:locality].to_s,
        demand: @demand.id.to_s
      })
      if params[:lat] && params[:lng]
        add_lat_and_lng_to_demand(@demand.id.to_s, params[:lat], params[:lng])
      end
      if params[:locality]
        add_locality_to_demand(@demand.id.to_s,params[:locality])
      end
      render "map/map", layout: 'map'
    end

  end

  def map_edit
    @demand_id = params[:demand_id]
    @demand = Demand.find(@demand_id.to_s)
    gon.push({
      lat: @demand.localisation_lat,
      lng: @demand.localisation_lng,
      city: @demand.localisation,
      origin: "edit",
      demand: @demand.id.to_s
    })
    render "map/map-edit", layout: 'map'
  end

  def restricted_demand_map
    render "map/restricted_demand_map", layout: 'map'
  end


  def nearby_zip_codes
    demand_id = params[:demand_id].to_s
    postal_codes = []
    integer_radius = (params[:radius].to_f) / 1000
    radius = integer_radius.round(0)
    get_zipcode_list = RestClient.get("https://www.villes-voisines.fr/getcp.php?cp=#{params[:postal_code]}&rayon=#{radius}")
    result_array = get_zipcode_list.body
    results = parse_zipcodes_result_json(result_array)

    if results.is_a?(Array)

      add_locality_to_demand(demand_id,results.last)

      if results.first != []
        add_postal_codes_to_demand(demand_id,results.first)
      else
        add_postal_codes_to_demand(demand_id,[params[:postal_code]])
      end
      params[:only_zipcode] = results.first
      render :json => params.to_json
    elsif results.is_a?(FalseClass)
      params[:only_zipcode] = results
      render json: {status: "failed"}
    end
  end

  private

  def parse_zipcodes_result(results)
    only_zipcode = []
    results.each do |result|
      parsing = result.split(',').map {|item| item if item != ""}.compact
      (zipcode = parsing[0].gsub(/[^0-9]/, '').to_i) if parsing[0]
      (city = parsing[1].split(":").last.gsub('"', '')) if parsing[1]
      if zipcode != 0 && city != nil
        only_zipcode << zipcode
      end
    end
    only_zipcode.uniq
  end


  def parse_zipcodes_result_json(results)
    if results == "null"
      return false
    end
    @json = JSON.parse(results.to_s)
    @results = {}
    only_zipcode = []
    @json.each do |result|

      puts "€€€€€€€€€€€€€"
      puts "#{result}"
      puts "€€€€€€€€€€€€€"

      if result.is_a?(Array)
        zipcode = result.last["code_postal"]
        city_name = result.last["nom_commune"]
      elsif result.is_a?(Hash)
        zipcode = result["code_postal"]
        city_name = result["nom_commune"]
      end


      if zipcode.to_s.chars.to_a.size == 5 && zipcode != "0"
        only_zipcode << zipcode
        if @results.has_key?(city_name.to_sym)
          @results[city_name.to_sym].push("#{zipcode}")
        else
          @results[city_name.to_sym] = ["#{zipcode}"]
        end
      end
    end
    formatted_localisation = format_localisation_string(@results)
    uniq_array = only_zipcode.uniq
    uniq_array
    return [uniq_array, formatted_localisation]
  end


  def format_localisation_string(results)
    all_results = []

    if results != {}
      results.each do |zipcode, city_collection|
        if city_collection.size == 1
          value = "#{zipcode} (#{city_collection.first})"
          all_results << value
        elsif city_collection.size == 2
          value = "#{zipcode} (#{city_collection.first} et #{city_collection.last})"
          all_results << value
        elsif city_collection.size > 2
          value = "#{zipcode} (#{city_collection[0..-2].join(', ')} et #{city_collection.last})"
          all_results << value
        end
      end
      return "#{all_results.join(', ')}"
    else
      return "Vide"
    end
  end


  def create_empty_demand
    if session[:bcs_customer_id]
      @customer = Customer.find(session[:bcs_customer_id])
      if @customer.demands.any?
        @demand = @customer.demands.last
      else
        @demand = Demand.new()
        @demand.customer = @customer
        @demand.save
      end
    else
      @demand = Demand.new()
      @customer = Customer.new()
      @demand.customer = @customer
      @demand.save
      @customer.save(validate: false)
      session[:bcs_customer_id] = @customer.id.to_s
    end
  end

  def add_postal_codes_to_demand(demand_id,results)
    @demand = Demand.find(demand_id)
    @demand.postal_codes = results.to_a.map{|zipcode| zipcode.to_s}
    @demand.save
  end

  def add_locality_to_demand(demand_id,locality)
    @demand = Demand.find(demand_id.to_s)
    @demand.localisation = locality.to_s
    @demand.save
  end

  def add_lat_and_lng_to_demand(demand_id, lat, lng)
    @demand = Demand.find(demand_id)
    @demand.localisation_lng = lng
    @demand.localisation_lat = lat
    @demand.save
  end

end

app/views/map/map-edit.html.haml
#map

/ MODAL AIDE
#modal_aide.modal.fade{tabindex: "-1",role: "dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-header
        / = image_tag "test", alt: "recherche immobilier"
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
      .modal-body.text-center
        %p
          %strong
            A droite
          avec les outils "Mes centres d’Intérêts", je peux faire apparaitre des informations clefs
          %br

          %strong
            A gauche
          avec les outils disponibles, je définie la zone où je souhaite habiter.
          %br

          %strong
            "Ma ville"
          je peux modifier cette dernière en cliquant sur l’outil "crayon" à côté du nom de la commune.
          %br

          %strong
            "Ma Zone de recherche"
          %br

          %strong
            Première étape :
          Je définie ma zone en cliquant sur l’outil "o". Je peux la modifier ou la supprimer ensuite avec les outils complémentaires qui apparaissent après avoir dessiné une première zone.
          %br

          %strong
            Deuxième étape :
          Si je le souhaite, je dessine d’autres zones de recherches. Je peux avoir plusieurs zones de recherche dans la même ville, ou sur des villes proches sur la carte affichée.
          %br

          %strong
            Troisième étape :
          Je poursuis ma demande, j’appuie sur le bouton "j’enregistre" pour préciser mon bien idéal

        %button.btn.btn-default.btn-validation{"data-dismiss":"modal"}
          OK, J'AI COMPRIS !


/ MODAL ENREGISTRE
#modal_enregistre.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        %p.text-center
          %strong
            Nous mettre en 4 (voire davantage), notre priorité !
          %br
          Excellent début. Votre choix est judicieux.
          %br
          Poursuivons, nous allons rapidement mieux vous connaitre
          et pourvoir ensuite vous aider à concrétiser votre projet immobilier !
        / = image_tag "test", alt: "recherche immobilier"
        = link_to "OUI, JE POURSUIS AU PLUS VITE !!", questionnaire_get_path(demand_id: @demand.id), class: "bcs-button-sm"



/ MODAL TROP DE CODES POSTAUX
#modal-exceed-perimeter.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-header
        / = image_tag "test", alt: "recherche immobilier"
        %button.close{type:"button","data-dismiss":"modal"}
          %span
            &times;
      .modal-body.text-center
        %p.text-center
          Votre zone de recherche est trop grande.
          %br
          Merci de réduire ou de supprimer des zones.
        %button.btn.btn-default.btn-validation{type:"button","data-dismiss":"modal"}
          OK, J'AI COMPRIS !


#modal-email-request.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        %p.text-center
          %strong
            Veuillez saisir votre e-mail
          %br
          Pour sauvergarder votre demande, nous avons besoin de votre email.
        / = image_tag "test", alt: "recherche immobilier"
        = link_to "JE VALIDE MON EMAIL", questionnaire_path, class: "bcs-button-sm"




#autocomplete-empty-result.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        .unfindable-address-container
          .city
          .content
        .bcs-button-sm{type:"button","data-dismiss":"modal"}
          ESSAYER UNE AUTRE ADRESSE




%script{src:'https://maps.googleapis.com/maps/api/js?key=AIzaSyCdpP4BuVUKk75HM7NENKCUgo7jwFMwQwA&libraries=places'}

app/views/map/map.html.haml
#map

/ MODAL AIDE
#modal_aide.modal.fade{tabindex: "-1",role: "dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-header
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
      .modal-body.text-center
        %p
          %strong
            A droite
          avec les outils "Mes centres d’Intérêts", je peux faire apparaitre des informations clefs
          %br

          %strong
            A gauche
          avec les outils disponibles, je définie la zone où je souhaite habiter.
          %br

          %strong
            "Ma ville"
          je peux modifier cette dernière en cliquant sur l’outil "crayon" à côté du nom de la commune.
          %br

          %strong
            "Ma Zone de recherche"
          %br

          %strong
            Première étape :
          Je définie ma zone en cliquant sur l’outil "o".
          Je peux ensuite la modifier ou la supprimer à l’aide des outils situés sur la palette de gauche de mon écran.
          %br

          %strong
            Deuxième étape :
          ça y est ma zone de recherche est correcte : je vais pouvoir passer à la suite en cliquant sur « J’enregistre ».

        %button.btn.btn-default.btn-validation{"data-dismiss":"modal"}
          OK, J'AI COMPRIS !


/ MODAL ENREGISTRE
#modal_enregistre.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close#modal-generic-close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        %p.text-center.modal-content-text
          Localisation validée ! Il ne me reste plus qu’à décrire le bien qui fera chavirer mon cœur ❤️
        = link_to "JE POURSUIS !!", questionnaire_get_path(demand_id: @demand.id), class: "bcs-button-sm mt-25"



#modal_results.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body
      .modal-footer
        .d-flex-center
          .progress-title.hidden
            Recherche des agences impactées ...
        .progress-container.hidden.d-flex-center
          .progress-text.bold
            0%
          .progress
            .progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "60", :role => "progressbar", :style => "width: 0%;"}
        .d-flex-center.links-progress-map.hidden
          .bcs-button-sm.mr-10{"data-dismiss": "modal"}
            JE MODIFIE
          = link_to "JE POURSUIS", questionnaire_get_path(demand_id: @demand.id), class: "bcs-button-sm"


#modal_empty_results.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body
      .modal-footer
        .d-flex-center
          .bcs-button-sm{"data-dismiss": "modal"}
            JE MODIFIE



#modal_waiting.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body
        .d-flex-center
          .bold
            Calcul en cours
        .d-flex-center
          .fa.fa-refresh.fa-spin



/ MODAL TROP DE CODES POSTAUX
#modal-exceed-perimeter.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-header
        / = image_tag "test", alt: "recherche immobilier"
        %button.close{type:"button","data-dismiss":"modal"}
          %span
            &times;
      .modal-body.text-center
        %p.text-center
          Votre zone de recherche est trop grande.
          %br
          Merci de réduire ou de supprimer des zones.
        %button.btn.btn-default.btn-validation{type:"button","data-dismiss":"modal"}
          OK, J'AI COMPRIS !


#modal-email-request.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        %p.text-center
          %strong
            Veuillez saisir votre e-mail
          %br
          Pour sauvergarder votre demande, nous avons besoin de votre email.
        / = image_tag "test", alt: "recherche immobilier"
        = link_to "JE VALIDE MON EMAIL", questionnaire_path, class: "bcs-button-sm"




#autocomplete-empty-result.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-body.text-center
        %button.close{type:"button","data-dismiss":"modal","aria-label":"close"}
          %span
            &times;
        .unfindable-address-container
          .city
          .content
        .bcs-button-sm{type:"button","data-dismiss":"modal"}
          ESSAYER UNE AUTRE ADRESSE


#unknowed-location.modal.fade{tabindex:"-1",role:"dialog"}
  .modal-dialog{role:"document"}
    .modal-content
      .modal-header
        %button.close{type:"button","data-dismiss":"modal"}
          %span
            &times;
      .modal-body.text-center
        %p.text-center
          Localisation inconnue. La zone de recherche est limitée à la france
          %br
          Merci de changer de zone.
        %button.btn.btn-default.btn-validation{type:"button","data-dismiss":"modal"}
          OK, J'AI COMPRIS !



%script{src:'https://maps.googleapis.com/maps/api/js?key=AIzaSyCdpP4BuVUKk75HM7NENKCUgo7jwFMwQwA&libraries=places'}

app/views/map/restricted_demand_map.html.haml
#map

#map-custom-modal.custom-modal-container.hidden
  .custom-modal
    .custom-modal-photo
      = image_tag "https://cdn.bientotchezsoi-dev.com/images/kenotte-spinner.svg", width: "140"
    .custom-modal-text
      %strong
        = "Oupss, vous avez déjà une demande active en cours !!"
    .d-flex-center.mt-25
      = link_to "Votre espace personnel", customer_zone_path, class: "bcs-button-very-small"

%script{src:'https://maps.googleapis.com/maps/api/js?key=AIzaSyCdpP4BuVUKk75HM7NENKCUgo7jwFMwQwA&libraries=places'}